"""
Unit tests for build_with_subquery: verify SQL generated by incremental_insert and iceberg_merge.
"""

import os
import re
from unittest import mock

import jinja2


_INCREMENTAL_DIR = os.path.normpath(
    os.path.join(
        os.path.dirname(__file__),
        os.pardir,
        os.pardir,
        "src",
        "dbt",
        "include",
        "athena",
        "macros",
        "materializations",
        "models",
        "incremental",
    )
)


class MockRelation:
    def __init__(self, name):
        self._name = name

    def __str__(self):
        return self._name


class MockColumn:
    def __init__(self, name):
        self.name = name
        self.column = name
        self.quoted = f'"{name}"'
        self.data_type = "varchar"


def _normalize(sql):
    return " ".join(sql.strip().split())


class MockAdapter:
    def __init__(self, columns, query_result):
        self._columns = columns
        self._query_result = query_result
        self.last_sql = None

    def get_columns_in_relation(self, relation):
        return self._columns

    def run_query_with_partitions_limit_catching(self, sql):
        self.last_sql = str(sql).strip()
        return self._query_result

    def is_list(self, x):
        return isinstance(x, list)


def _build_context(query_result="OK"):
    columns = [MockColumn("id"), MockColumn("msg"), MockColumn("color")]
    adapter = MockAdapter(columns, query_result)

    context = {
        "adapter": adapter,
        "config": mock.Mock(),
        "log": lambda *args, **kwargs: "",
        "run_query": lambda sql: "",
        "exceptions": mock.Mock(),
        "process_schema_changes": lambda *a, **kw: columns,
        "get_partition_batches": lambda *a, **kw: [],
    }
    context["config"].get = lambda key, *args, **kwargs: kwargs.get(
        "default", args[0] if args else None
    )
    return adapter, context


def _load_patched_merge_sql():
    """Load merge.sql with get_merge_update_columns and get_update_statement
    replaced by simple Jinja2-compatible stubs (no return() needed)."""
    with open(os.path.join(_INCREMENTAL_DIR, "merge.sql")) as f:
        src = f.read()

    # Replace get_merge_update_columns call with direct assignment (avoids return() issue)
    src = src.replace(
        "get_merge_update_columns(merge_update_columns, merge_exclude_columns, dest_columns_wo_keys)",
        "dest_columns_wo_keys",
    )

    # Replace get_update_statement: simple replace rule
    src = re.sub(
        r"\{%-?\s*macro get_update_statement\(.*?%\}.*?\{%-?\s*endmacro\s*-?%\}",
        (
            "{%- macro get_update_statement(col, rule, is_last) -%}"
            '{{ col.quoted }} = src.{{ col.quoted }}{{ "" if is_last else "," }}'
            "{%- endmacro -%}"
        ),
        src,
        flags=re.DOTALL,
    )

    return src


def _render_incremental_insert(source_sql=None, query_result="OK"):
    adapter, context = _build_context(query_result=query_result)

    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(_INCREMENTAL_DIR),
        extensions=["jinja2.ext.do"],
    )
    helpers = env.get_template("helpers.sql", globals=context)

    helpers.module.incremental_insert(
        on_schema_change="ignore",
        tmp_relation=MockRelation("db.schema.tbl__dbt_tmp"),
        target_relation=MockRelation("db.schema.tbl"),
        existing_relation=MockRelation("db.schema.tbl"),
        force_batch=False,
        source_sql=source_sql,
    )
    return adapter, context


def _render_iceberg_merge(source_sql=None, query_result="OK"):
    adapter, context = _build_context(query_result=query_result)

    patched_src = _load_patched_merge_sql()
    env = jinja2.Environment(
        loader=jinja2.DictLoader({"merge.sql": patched_src}),
        extensions=["jinja2.ext.do"],
    )
    merge_tpl = env.get_template("merge.sql", globals=context)

    merge_tpl.module.iceberg_merge(
        on_schema_change="ignore",
        tmp_relation=MockRelation("db.schema.tbl__dbt_tmp"),
        target_relation=MockRelation("db.schema.tbl"),
        unique_key="id",
        incremental_predicates=None,
        existing_relation=MockRelation("db.schema.tbl"),
        delete_condition=None,
        update_condition=None,
        insert_condition=None,
        force_batch=False,
        source_sql=source_sql,
    )
    return adapter, context


# --- incremental_insert ---


class TestIncrementalInsertWithSubquery:
    def test_insert_uses_subquery(self):
        adapter, _ = _render_incremental_insert(source_sql="SELECT id, msg, color FROM src")
        assert _normalize(adapter.last_sql) == (
            'insert into db.schema.tbl ("id", "msg", "color")'
            " ( select"
            ' "id", "msg", "color"'
            " from (SELECT id, msg, color FROM src) _dbt_sbq );"
        )

    def test_insert_without_subquery_uses_tmp_relation(self):
        adapter, _ = _render_incremental_insert()
        assert _normalize(adapter.last_sql) == (
            'insert into db.schema.tbl ("id", "msg", "color")'
            " ( select"
            ' "id", "msg", "color"'
            " from db.schema.tbl__dbt_tmp );"
        )

    def test_subquery_too_many_partitions_raises_error(self):
        _, context = _render_incremental_insert(
            source_sql="SELECT 1", query_result="TOO_MANY_OPEN_PARTITIONS"
        )
        context["exceptions"].raise_compiler_error.assert_called_once()
        error_msg = context["exceptions"].raise_compiler_error.call_args[0][0]
        assert "TOO_MANY_OPEN_PARTITIONS" in error_msg
        assert "build_with_subquery" in error_msg

    def test_without_subquery_too_many_partitions_falls_back_to_batch(self):
        _, context = _render_incremental_insert(query_result="TOO_MANY_OPEN_PARTITIONS")
        context["exceptions"].raise_compiler_error.assert_not_called()


# --- iceberg_merge ---

_EXPECTED_MERGE_CLAUSES = (
    " on (target.id = src.id )"
    " when matched"
    ' then update set"msg" = src."msg","color" = src."color"'
    ' when not matched then insert ("id", "msg", "color")'
    ' values (src."id", src."msg", src."color")'
)


class TestIcebergMergeWithSubquery:
    def test_merge_uses_subquery(self):
        adapter, _ = _render_iceberg_merge(source_sql="SELECT id, msg, color FROM src")
        assert _normalize(adapter.last_sql) == (
            "merge into db.schema.tbl as target"
            " using (SELECT id, msg, color FROM src) as src" + _EXPECTED_MERGE_CLAUSES
        )

    def test_merge_without_subquery_uses_tmp_relation(self):
        adapter, _ = _render_iceberg_merge()
        assert _normalize(adapter.last_sql) == (
            "merge into db.schema.tbl as target"
            " using db.schema.tbl__dbt_tmp as src" + _EXPECTED_MERGE_CLAUSES
        )

    def test_subquery_too_many_partitions_raises_error(self):
        _, context = _render_iceberg_merge(
            source_sql="SELECT 1", query_result="TOO_MANY_OPEN_PARTITIONS"
        )
        context["exceptions"].raise_compiler_error.assert_called_once()
        error_msg = context["exceptions"].raise_compiler_error.call_args[0][0]
        assert "TOO_MANY_OPEN_PARTITIONS" in error_msg
        assert "build_with_subquery" in error_msg

    def test_without_subquery_too_many_partitions_falls_back_to_batch(self):
        _, context = _render_iceberg_merge(query_result="TOO_MANY_OPEN_PARTITIONS")
        context["exceptions"].raise_compiler_error.assert_not_called()
