"""
Unit tests for build_with_subquery: verify SQL generated by incremental_insert and iceberg_merge.
"""

import os
import re
from unittest import mock

import jinja2


_MACROS_DIR = os.path.normpath(
    os.path.join(
        os.path.dirname(__file__),
        os.pardir,
        os.pardir,
        "src",
        "dbt",
        "include",
        "athena",
        "macros",
        "materializations",
        "models",
    )
)
_INCREMENTAL_DIR = os.path.join(_MACROS_DIR, "incremental")
_TABLE_DIR = os.path.join(_MACROS_DIR, "table")
_INCREMENTAL_SQL_PATH = os.path.join(_INCREMENTAL_DIR, "incremental.sql")
_CREATE_TABLE_AS_SQL_PATH = os.path.join(_TABLE_DIR, "create_table_as.sql")


class MockRelation:
    def __init__(self, name):
        self._name = name

    def __str__(self):
        return self._name


class MockColumn:
    def __init__(self, name):
        self.name = name
        self.column = name
        self.quoted = f'"{name}"'
        self.data_type = "varchar"


def _normalize_sql_lines(sql):
    """Strip per-line leading/trailing whitespace and drop blank lines. SQL
    semantics don't depend on indentation or blank lines outside of string
    literals, so this lets expected heredocs ignore Jinja's incidental
    whitespace while still asserting line structure (ordering, content) exactly."""
    return "\n".join(stripped for line in sql.splitlines() if (stripped := line.strip()))


def _assert_sql_equal(actual, expected):
    """Compare SQL line-by-line, ignoring per-line whitespace and blank lines."""
    assert _normalize_sql_lines(actual) == _normalize_sql_lines(expected)


_EXPECTED_MERGE_TAIL = """\
    on (target.id = src.id
    )
    when matched
        then update set"msg" = src."msg","color" = src."color"
    when not matched
        then insert ("id", "msg", "color")
        values (src."id", src."msg", src."color")"""


class MockAdapter:
    def __init__(self, columns, query_result):
        self._columns = columns
        self._query_result = query_result
        self.last_sql = None

    def get_columns_in_relation(self, relation):
        return self._columns

    def run_query_with_partitions_limit_catching(self, sql):
        self.last_sql = str(sql).strip()
        return self._query_result

    def is_list(self, x):
        return isinstance(x, list)


def _build_context(query_result="OK"):
    columns = [MockColumn("id"), MockColumn("msg"), MockColumn("color")]
    adapter = MockAdapter(columns, query_result)

    context = {
        "adapter": adapter,
        "config": mock.Mock(),
        "log": lambda *args, **kwargs: "",
        "run_query": lambda sql: "",
        "exceptions": mock.Mock(),
        "process_schema_changes": lambda *a, **kw: columns,
        "get_partition_batches": lambda *a, **kw: [],
    }
    context["config"].get = lambda key, *args, **kwargs: kwargs.get(
        "default", args[0] if args else None
    )
    return adapter, context


def _load_patched_merge_sql():
    """Load merge.sql with get_merge_update_columns and get_update_statement
    replaced by simple Jinja2-compatible stubs (no return() needed)."""
    with open(os.path.join(_INCREMENTAL_DIR, "merge.sql")) as f:
        src = f.read()

    # Replace get_merge_update_columns call with direct assignment (avoids return() issue)
    src = src.replace(
        "get_merge_update_columns(merge_update_columns, merge_exclude_columns, dest_columns_wo_keys)",
        "dest_columns_wo_keys",
    )

    # Replace get_update_statement: simple replace rule
    src = re.sub(
        r"\{%-?\s*macro get_update_statement\(.*?%\}.*?\{%-?\s*endmacro\s*-?%\}",
        (
            "{%- macro get_update_statement(col, rule, is_last) -%}"
            '{{ col.quoted }} = src.{{ col.quoted }}{{ "" if is_last else "," }}'
            "{%- endmacro -%}"
        ),
        src,
        flags=re.DOTALL,
    )

    return src


def _render_incremental_insert(source_sql=None, query_result="OK"):
    adapter, context = _build_context(query_result=query_result)

    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(_INCREMENTAL_DIR),
        extensions=["jinja2.ext.do"],
    )
    helpers = env.get_template("helpers.sql", globals=context)

    helpers.module.incremental_insert(
        on_schema_change="ignore",
        tmp_relation=MockRelation("db.schema.tbl__dbt_tmp"),
        target_relation=MockRelation("db.schema.tbl"),
        existing_relation=MockRelation("db.schema.tbl"),
        force_batch=False,
        source_sql=source_sql,
    )
    return adapter, context


def _render_iceberg_merge(source_sql=None, query_result="OK"):
    adapter, context = _build_context(query_result=query_result)

    patched_src = _load_patched_merge_sql()
    env = jinja2.Environment(
        loader=jinja2.DictLoader({"merge.sql": patched_src}),
        extensions=["jinja2.ext.do"],
    )
    merge_tpl = env.get_template("merge.sql", globals=context)

    merge_tpl.module.iceberg_merge(
        on_schema_change="ignore",
        tmp_relation=MockRelation("db.schema.tbl__dbt_tmp"),
        target_relation=MockRelation("db.schema.tbl"),
        unique_key="id",
        incremental_predicates=None,
        existing_relation=MockRelation("db.schema.tbl"),
        delete_condition=None,
        update_condition=None,
        insert_condition=None,
        force_batch=False,
        source_sql=source_sql,
    )
    return adapter, context


# --- incremental_insert ---


class TestIncrementalInsertWithSubquery:
    def test_insert_uses_subquery(self):
        adapter, _ = _render_incremental_insert(source_sql="SELECT id, msg, color FROM src")
        _assert_sql_equal(
            adapter.last_sql,
            """\
            insert into db.schema.tbl ("id", "msg", "color")
                (
                    select "id", "msg", "color"
                    from (
                        SELECT id, msg, color FROM src
                    ) _dbt_sbq
                );""",
        )

    def test_insert_subquery_isolates_trailing_line_comment(self):
        """A trailing line comment in source_sql must not swallow the closing
        paren of the subquery wrapper. Full SQL is asserted so any regression
        in whitespace/newline handling is caught."""
        source_sql = "SELECT id, msg, color FROM src -- trailing comment"
        adapter, _ = _render_incremental_insert(source_sql=source_sql)
        _assert_sql_equal(
            adapter.last_sql,
            """\
            insert into db.schema.tbl ("id", "msg", "color")
                (
                    select "id", "msg", "color"
                    from (
                        SELECT id, msg, color FROM src -- trailing comment
                    ) _dbt_sbq
                );""",
        )

    def test_insert_without_subquery_uses_tmp_relation(self):
        adapter, _ = _render_incremental_insert()
        _assert_sql_equal(
            adapter.last_sql,
            """\
            insert into db.schema.tbl ("id", "msg", "color")
                (
                    select "id", "msg", "color"
                    from db.schema.tbl__dbt_tmp
                );""",
        )

    def test_subquery_too_many_partitions_raises_error(self):
        _, context = _render_incremental_insert(
            source_sql="SELECT 1", query_result="TOO_MANY_OPEN_PARTITIONS"
        )
        context["exceptions"].raise_compiler_error.assert_called_once()
        error_msg = context["exceptions"].raise_compiler_error.call_args[0][0]
        assert "TOO_MANY_OPEN_PARTITIONS" in error_msg
        assert "build_with_subquery" in error_msg

    def test_without_subquery_too_many_partitions_falls_back_to_batch(self):
        _, context = _render_incremental_insert(query_result="TOO_MANY_OPEN_PARTITIONS")
        context["exceptions"].raise_compiler_error.assert_not_called()


# --- iceberg_merge ---


class TestIcebergMergeWithSubquery:
    def test_merge_uses_subquery(self):
        adapter, _ = _render_iceberg_merge(source_sql="SELECT id, msg, color FROM src")
        _assert_sql_equal(
            adapter.last_sql,
            """\
            merge into db.schema.tbl as target using (
                SELECT id, msg, color FROM src
            ) as src
            """
            + _EXPECTED_MERGE_TAIL,
        )

    def test_merge_subquery_isolates_trailing_line_comment(self):
        """A trailing line comment in source_sql must not swallow the closing
        paren of the subquery wrapper. Full SQL is asserted so any regression
        in whitespace/newline handling is caught."""
        source_sql = "SELECT id, msg, color FROM src -- trailing comment"
        adapter, _ = _render_iceberg_merge(source_sql=source_sql)
        _assert_sql_equal(
            adapter.last_sql,
            """\
            merge into db.schema.tbl as target using (
                SELECT id, msg, color FROM src -- trailing comment
            ) as src
            """
            + _EXPECTED_MERGE_TAIL,
        )

    def test_merge_without_subquery_uses_tmp_relation(self):
        adapter, _ = _render_iceberg_merge()
        _assert_sql_equal(
            adapter.last_sql,
            "merge into db.schema.tbl as target using db.schema.tbl__dbt_tmp as src\n"
            + _EXPECTED_MERGE_TAIL,
        )

    def test_subquery_too_many_partitions_raises_error(self):
        _, context = _render_iceberg_merge(
            source_sql="SELECT 1", query_result="TOO_MANY_OPEN_PARTITIONS"
        )
        context["exceptions"].raise_compiler_error.assert_called_once()
        error_msg = context["exceptions"].raise_compiler_error.call_args[0][0]
        assert "TOO_MANY_OPEN_PARTITIONS" in error_msg
        assert "build_with_subquery" in error_msg

    def test_without_subquery_too_many_partitions_falls_back_to_batch(self):
        _, context = _render_iceberg_merge(query_result="TOO_MANY_OPEN_PARTITIONS")
        context["exceptions"].raise_compiler_error.assert_not_called()


# --- empty_sql in incremental.sql ---


def _render_empty_sql(compiled_code):
    """Render the same `{% set empty_sql ... %}` Jinja expression that lives in
    incremental.sql for the build_with_subquery branches. We extract it from the
    real file so the test catches drift if the line is rewritten."""
    with open(_INCREMENTAL_SQL_PATH) as f:
        src = f.read()
    matches = re.findall(r"\{%-?\s*set\s+empty_sql\s*=.*?-?%\}", src)
    assert matches, "expected at least one `{% set empty_sql = ... %}` in incremental.sql"
    rendered = []
    env = jinja2.Environment(extensions=["jinja2.ext.do"])
    for fragment in matches:
        template_src = fragment + "{{ empty_sql }}"
        rendered.append(env.from_string(template_src).render(compiled_code=compiled_code))
    return rendered


class TestEmptySqlSubqueryWrapping:
    def test_empty_sql_wraps_compiled_code(self):
        renderings = _render_empty_sql("SELECT 1 AS id")
        assert renderings, "no empty_sql fragments rendered"
        expected = """\
            SELECT * FROM (
                SELECT 1 AS id
            ) _dbt_sbq WITH NO DATA"""
        for rendered in renderings:
            _assert_sql_equal(rendered, expected)

    def test_empty_sql_isolates_trailing_line_comment(self):
        """The closing paren of empty_sql must land on a fresh line so a
        trailing -- line comment in compiled_code cannot comment it out."""
        compiled_code = "SELECT 1 AS id\n-- trailing comment"
        renderings = _render_empty_sql(compiled_code)
        assert renderings, "no empty_sql fragments rendered"
        expected = """\
            SELECT * FROM (
                SELECT 1 AS id
                -- trailing comment
            ) _dbt_sbq WITH NO DATA"""
        for rendered in renderings:
            _assert_sql_equal(rendered, expected)


# --- empty_sql in create_table_as.sql ---


def _render_table_empty_sql(compiled_code):
    """Render the `{% set empty_sql ... %}` expression from create_table_as.sql."""
    with open(_CREATE_TABLE_AS_SQL_PATH) as f:
        src = f.read()
    matches = re.findall(r"\{%-?\s*set\s+empty_sql\s*=.*?-?%\}", src)
    assert matches, "expected at least one `{% set empty_sql = ... %}` in create_table_as.sql"
    rendered = []
    env = jinja2.Environment(extensions=["jinja2.ext.do"])
    for fragment in matches:
        template_src = fragment + "{{ empty_sql }}"
        rendered.append(env.from_string(template_src).render(compiled_code=compiled_code))
    return rendered


class TestTableEmptySqlSubqueryWrapping:
    def test_empty_sql_wraps_compiled_code(self):
        renderings = _render_table_empty_sql("SELECT 1 AS id")
        assert renderings, "no empty_sql fragments rendered"
        expected = """\
            SELECT * FROM (
                SELECT 1 AS id
            ) _dbt_sbq WITH NO DATA"""
        for rendered in renderings:
            _assert_sql_equal(rendered, expected)

    def test_empty_sql_isolates_trailing_line_comment(self):
        compiled_code = "SELECT 1 AS id\n-- trailing comment"
        renderings = _render_table_empty_sql(compiled_code)
        assert renderings, "no empty_sql fragments rendered"
        expected = """\
            SELECT * FROM (
                SELECT 1 AS id
                -- trailing comment
            ) _dbt_sbq WITH NO DATA"""
        for rendered in renderings:
            _assert_sql_equal(rendered, expected)
