changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
envPrefix: CHANGIE_
versionFormat: '## dbt-adapter {{.Version}} - {{.Time.Format "January 02, 2006"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* {{.Body}}'
kinds:
  - label: Breaking Changes
  - label: Features
  - label: Fixes
  - label: Docs
  - label: Under the Hood
  - label: Dependencies
  - label: Security
newlines:
  afterChangelogHeader: 1
  afterKind: 1
  afterChangelogVersion: 1
  beforeKind: 1
  endOfVersion: 1

custom:
- key: Author
  label: GitHub Username(s) (separated by a single space if multiple)
  type: string
  minLength: 3
- key: Issue
  label: GitHub Issue Number (separated by a single space if multiple)
  type: string
  minLength: 1
