changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
versionExt: md
envPrefix: CHANGIE_
versionFormat: '## dbt-adapters {{.Version}} - {{.Time.Format "January 02, 2006"}}'
kindFormat: '### {{.Kind}}'
changeFormat: |-
  {{- $IssueList := list }}
  {{- $changes := splitList " " $.Custom.Issue }}
  {{- range $issueNbr := $changes }}
    {{- $changeLink := "[#nbr](https://github.com/dbt-labs/dbt-adapters/issues/nbr)" | replace "nbr" $issueNbr }}
    {{- $IssueList = append $IssueList $changeLink  }}
  {{- end -}}
  - {{.Body}} ({{ range $index, $element := $IssueList }}{{if $index}}, {{end}}{{$element}}{{end}})
kinds:
- label: Breaking Changes
- label: Features
- label: Fixes
- label: Docs
- label: Under the Hood
- label: Dependencies
  changeFormat: |-
    {{- $PRList := list }}
    {{- $changes := splitList " " $.Custom.PR }}
    {{- range $pullrequest := $changes }}
      {{- $changeLink := "[#nbr](https://github.com/dbt-labs/dbt-adapters/pull/nbr)" | replace "nbr" $pullrequest }}
      {{- $PRList = append $PRList $changeLink  }}
    {{- end -}}
    - {{.Body}} ({{ range $index, $element := $PRList }}{{if $index}}, {{end}}{{$element}}{{end}})
  skipGlobalChoices: true
  additionalChoices:
  - key: Author
    label: GitHub Username(s) (separated by a single space if multiple)
    type: string
    minLength: 3
  - key: PR
    label: GitHub Pull Request Number (separated by a single space if multiple)
    type: string
    minLength: 1
- label: Security
  changeFormat: |-
    {{- $PRList := list }}
    {{- $changes := splitList " " $.Custom.PR }}
    {{- range $pullrequest := $changes }}
      {{- $changeLink := "[#nbr](https://github.com/dbt-labs/dbt-adapters/pull/nbr)" | replace "nbr" $pullrequest }}
      {{- $PRList = append $PRList $changeLink  }}
    {{- end -}}
    - {{.Body}} ({{ range $index, $element := $PRList }}{{if $index}}, {{end}}{{$element}}{{end}})
  skipGlobalChoices: true
  additionalChoices:
  - key: Author
    label: GitHub Username(s) (separated by a single space if multiple)
    type: string
    minLength: 3
  - key: PR
    label: GitHub Pull Request Number (separated by a single space if multiple)
    type: string
    minLength: 1
newlines:
  afterChangelogHeader: 1
  afterKind: 1
  afterChangelogVersion: 1
  beforeKind: 1
  endOfVersion: 1
custom:
- key: Author
  label: GitHub Username(s) (separated by a single space if multiple)
  type: string
  minLength: 3
- key: Issue
  label: GitHub Issue Number (separated by a single space if multiple)
  type: string
  minLength: 1
