name: Setup `hatch`

inputs:
  python-version:
    description: Create an environment with the appropriate version of python and hatch installed
    default: "3.11"
  setup-command:
    description: The command to setup development dependencies
    default: "python -m pip install hatch"

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install hatch
      run: ${{ inputs.setup-command }}
      shell: bash
