name: Setup `hatch`

inputs:
  setup-command:
    description: The command to setup development dependencies
    default: "python -m pip install hatch"

runs:
  using: composite
  steps:
    - name: Set up Python ${{ vars.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ vars.PYTHON_VERSION }}

    - name: Install dev dependencies
      run: ${{ inputs.setup-command }}
      shell: bash
