name: Setup `hatch`

inputs:
  python-version:
    description: Create an environment with the appropriate version of python and hatch installed
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install hatch
      run: python -m pip install hatch
      shell: bash
