name: Build - `hatch`
description: Build artifacts using the `hatch` build backend

inputs:
  build-command:
    description: The command to build distributable artifacts
    default: "hatch build"
  check-command:
    description: The command to check built artifacts
    default: "hatch run build:check-all"
  working-dir:
    description: Where to run commands from, supports namespace packaging
    default: "./"
  archive-name:
    description: Where to upload the artifacts
    default: ""

runs:
  using: composite
  steps:

    - name: Build artifacts
      run: ${{ inputs.build-command }}
      shell: bash
      working-directory: ${{ inputs.working-dir }}

    - name: Check artifacts
      run: ${{ inputs.check-command }}
      shell: bash
      working-directory: ${{ inputs.working-dir }}

    - name: Upload artifacts
      if: ${{ inputs.archive-name != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.archive-name }}
        path: ${{ inputs.working-dir }}dist/
        retention-days: 3
