name: Publish - PyPI
description: Publish artifacts saved during build step to PyPI

inputs:
  artifacts-dir:
    description: Where to download the artifacts
    default: "/dist"
  pypi-repository-url:
    description: The PyPI index to publish to, test or prod
    required: true

runs:
  using: composite
  steps:

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifacts-dir }}
        path: dist/

    - name: Publish artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ inputs.pypi-repository-url }}
