name: Publish PyPI

inputs:
  deploy-to:
    description: The PyPI index to publish to, test or prod
    default: "prod"
  build-command:
    description: The command to build distributable artifacts
    default: "hatch build"
  check-command:
    description: The command to check built artifacts
    default: "hatch run build:check-all"

runs:
  using: composite
  steps:
    - name: Build artifacts
      run: ${{ inputs.build-command }}
      shell: bash

    - name: Check artifacts
      run: ${{ inputs.check-command }}
      shell: bash

    - name: Publish artifacts
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        url: ${{ vars.PYPI_REPOSITORY_URL }}
