name: Publish PyPI

inputs:
  python-version:
    description: Create an environment with the appropriate version of python and hatch installed
    default: "3.11"

runs:
  using: composite
  steps:
    - name: Setup environment
      uses: ./.github/actions/setup-environment
      with:
        python-version: ${{ inputs.python-version }}

    - name: Build artifacts
      run: hatch build
      shell: bash

    - name: Check artifacts
      run: hatch run build:check-all
      shell: bash

    - name: Publish artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
