name: Publish PyPI

inputs:
  pypi-repository-url:
    description: The PyPI index to publish to, test or prod
    required: true
  build-command:
    description: The command to build distributable artifacts
    default: "hatch build"
  check-command:
    description: The command to check built artifacts
    default: "hatch run build:check-all"

runs:
  using: composite
  steps:
    - name: Check current directory
      run: pwd
      shell: bash

    - name: Build artifacts
      run: ${{ inputs.build-command }}
      shell: bash

    - name: Check artifacts
      run: ${{ inputs.check-command }}
      shell: bash

    - name: Publish artifacts
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ inputs.pypi-repository-url }}
