name: 🛠️ Feature Implementation
description: This is a feature implementation ticket intended for use by the maintainers of `dbt-adapters`
title: "[<project>] <title>"
labels: ["user docs","enhancement","refinement"]
body:
  - type: markdown
    attributes:
      value: This is a feature implementation ticket intended for use by the maintainers of `dbt-adapters`

  - type: checkboxes
    attributes:
      label: Housekeeping
      description: >
        A couple friendly reminders:
          1. Remove the `user docs` label if the scope of this work does not require changes to https://docs.getdbt.com/docs: no end-user interface (e.g. yml spec, CLI, error messages, etc) or functional changes.
          2. Only remove the `refinement` label if you're confident this is ready to estimate and/or you've received feedback from at least one other engineer.
          3. Will this change need to be backported? Add the appropriate `backport 1.x.latest` label(s).
          4. Will this impact other teams? Add the appropriate `Impact:[Team]` labels.
      options:
        - label: I am a maintainer of `dbt-adapters`
          required: true

  - type: textarea
    attributes:
      label: Short description
      description: |
        Describe the scope of this feature, a high-level implementation approach and any tradeoffs to consider.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Context
      description: |
        Provide the "why", motivation, and alternative approaches considered -- linking to previous refinement issues, spikes and documentation as appropriate.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Acceptance criteria
      description: |
        What is the definition of done for this feature? Include any relevant edge cases and/or test cases.
        
        Example:
        - [ ] If there are no config changes, don't alter the materialized view
        - [ ] If the materialized view is scheduled to refresh, a manual refresh should not be issued
      value: |
        ```[tasklist]
        - [ ] Criterion
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Testing
      description: |
        Provide scenarios to test. Include both positive and negative tests if possible.
        Link to existing similar tests if appropriate.
        
        Example:
         - [ ] Test with no `materialized` field in the model config. Expect pass.
         - [ ] Test with a `materialized` field in the model config that is not valid. Expect ConfigError.
      value: |
        ```[tasklist]
         - [ ] Test
        ```
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Security
      description: |
        Are there any security concerns with these changes?
        When in doubt, run it by the security team.
      placeholder: |
        Example: Logging sensitive data
    validations:
      required: true

  - type: textarea
    attributes:
      label: Docs
      description: |
        Are there any docs the will need to be added or updated?
      placeholder: |
        Example: We need to document how to configure this new authentication method.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Consequences
      description: |
        Will this impact dbt Labs' ability, or a partner's ability, to make a related change? Call that out for discussion.
        Review `Impact:<team>` labels to ensure they capture these consequences.
      placeholder: |
        Example:
        - This change impacts `dbt-databricks` because we updated a macro in `dbt-spark`. (Add the `Impact:[Databricks]` label.)
    validations:
      required: true
