name: 🧠️ Epic
description: This is an epic ticket intended for use by the maintainers and product managers of `dbt-adapters`
title: "[<project>] <title>"
labels: ["epic"]
body:
  - type: markdown
    attributes:
      value: This is an epic ticket intended for use by the maintainers and product managers of `dbt-adapters`

  - type: input
    attributes:
      label: Short description
      description: |
        What's the one-liner that would tell everyone what we're doing?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Context
      description: |
        Provide the "why". What's the motivation? Why are we doing it now?
        Will this apply to all adapters or does this support a specific subset (e.g. only SQL adapters, only Snowflake, etc.)?
        Is this updating existing functionality or providing all new functionality?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Objectives
      description: |
        What are the high level goals we are trying to achieve? Provide use cases if available.
        
        Example:
        - [ ] Allow adapter maintainers to support custom materializations
        - [ ] Reduce maintenance burden for incremental users by offering materialized views
      value: |
        ```[tasklist]
        - [ ] Objective
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Implementation tasks
      description: |
        Provide a list of GH issues that will build out this functionality.
        This may start empty, or as a checklist of items.
        However, it should eventually become a list of Feature Implementation tickets.
        
        Example:
        - [ ] Create new macro to select warehouse
        - [ ] https://github.com/dbt-labs/dbt-adapters/issues/42
      value: |
        ```[tasklist]
        - [ ] Task
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Documentation
      description: |
        Provide a list of relevant documentation. Is there a proof of concept?
        Does this require and RFCs, ADRs, etc.?
        If the documentation exists, link it; if it does not exist yet, reference it descriptively.
        
        Example:
        - [ ] RFC for updating connection interface to accept new parameters
        - [ ] POC: https://github.com/dbt-labs/dbt-adapters/pull/42
      value: |
        ```[tasklist]
        - [ ] Task
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Consequences
      description: |
        Will this impact dbt Labs' ability, or a partner's ability, to make a related change? Call that out for discussion.
        Review `Impact:<team>` labels to ensure they capture these consequences.
      placeholder: |
        Example:
        - This change impacts `dbt-core` because we updated how relations are managed. (Add the `Impact:[Core]` label.)
        - This allows internal analytics to do more robust analysis of infrastructure usage (Add the `Impact:[Analytics]` label.)
    validations:
      required: true
