CREATE DATABASE dbt;

CREATE ROLE root WITH PASSWORD 'password';
ALTER ROLE root WITH LOGIN;
GRANT CREATE, CONNECT ON DATABASE dbt TO root WITH GRANT OPTION;

CREATE ROLE noaccess WITH PASSWORD 'password' NOSUPERUSER;
ALTER ROLE noaccess WITH LOGIN;
GRANT CONNECT ON DATABASE dbt TO noaccess;

CREATE ROLE dbt_test_user_1;
CREATE ROLE dbt_test_user_2;
CREATE ROLE dbt_test_user_3;

CREATE DATABASE "dbtMixedCase";
GRANT CREATE, CONNECT ON DATABASE "dbtMixedCase" TO root WITH GRANT OPTION;
