name: hologres_example
version: '1.0.0'
config-version: 2

profile: 'hologres_example'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  hologres_example:
    staging:
      +materialized: table
      +schema: staging
    
    marts:
      +materialized: table
      +schema: marts
      
      # Example: Dynamic Table configuration
      orders_dynamic_table:
        +materialized: dynamic_table
        +freshness: "30 minutes"
        +auto_refresh_mode: auto
        +computing_resource: serverless
      
      # Example: Incremental model configuration
      orders_incremental:
        +materialized: incremental
        +unique_key: order_id
        +on_schema_change: "fail"
