[version]
path = "src/dbt/adapters/redshift/__version__.py"

[build.targets.sdist]
packages = ["src/dbt"]
sources = ["src"]

[build.targets.wheel]
packages = ["src/dbt"]
sources = ["src"]

[envs.default]
pre-install-commands = [
    "pip install -e ../dbt-adapters",
    "pip install -e ../dbt-tests-adapter",
    "pip install -e ../dbt-postgres",
]
dependencies = [
    "dbt-common @ git+https://github.com/dbt-labs/dbt-common.git",
    "dbt-core @ git+https://github.com/dbt-labs/dbt-core.git#subdirectory=core",
    "ddtrace==2.3.0",
    "freezegun",
    "ipdb~=0.13.13",
    "pre-commit==3.7.0",
    "pytest-csv~=3.0",
    "pytest-dotenv",
    "pytest-logbook~=1.2",
    "pytest-mock",
    "pytest-xdist",
    "pytest>=7.0,<8.0",
    "requests",
]

[envs.default.scripts]
setup = [
    "pre-commit install",
    "cp -n test.env.example test.env",
]
code-quality = "pre-commit run --all-files"
unit-tests = "python -m pytest {args:tests/unit}"
integration-tests = "python -m pytest {args:tests/functional}"
docker-dev = [
    "docker build -f docker/dev.Dockerfile -t dbt-redshift-dev .",
	"docker run --rm -it --name dbt-redshift-dev -v $(shell pwd):/opt/code dbt-redshift-dev",
]

[envs.build]
detached = true
dependencies = [
    "wheel",
    "twine",
    "check-wheel-contents",
]

[envs.build.scripts]
check-all = [
    "- check-wheel",
    "- check-sdist",
]
check-wheel = [
    "twine check dist/*",
    "find ./dist/dbt_redshift-*.whl -maxdepth 1 -type f | xargs python -m pip install --force-reinstall --find-links=dist/",
    "pip freeze | grep dbt-redshift",
]
check-sdist = [
    "check-wheel-contents dist/*.whl --ignore W007,W008",
    "find ./dist/dbt_redshift-*.gz -maxdepth 1 -type f | xargs python -m pip install --force-reinstall --find-links=dist/",
    "pip freeze | grep dbt-redshift",
]
docker-prod = "docker build -f docker/Dockerfile -t dbt-redshift ."
