"""Functional tests for the `drop_without_cascade` profile credential.

These exercise the rendered SQL by inspecting dbt's debug logs after a
re-run that forces a DROP. The first run creates the relation; the
second run drops + recreates it, surfacing the DROP statement in logs.

Note: schema names auto-generated by the test harness include the test
file name, which contains the substring "cascade". We therefore use
`\\bcascade\\b` (word boundary) when checking for the keyword so the
substring inside the schema name does not confound the assertion.
"""

import re

import pytest

from dbt.tests.util import run_dbt, run_dbt_and_capture


_VIEW_MODEL = """
{{ config(materialized='view') }}
select 1 as id
"""


# Word-boundary regex: `_cascade` inside a schema identifier is NOT a word
# boundary on the leading side, so this only matches the standalone keyword.
_CASCADE_KEYWORD = re.compile(r"\bcascade\b", re.IGNORECASE)


def _drop_view_lines(logs: str, relation_name: str) -> list:
    matches = []
    for line in logs.splitlines():
        lowered = line.lower()
        if "drop view if exists" in lowered and relation_name in lowered:
            matches.append(line)
    return matches


def _has_cascade_keyword(line: str) -> bool:
    # Strip the schema/identifier portion (anything inside double quotes) so
    # the test_drop_without_cascade schema name cannot trigger a false match.
    sanitized = re.sub(r'"[^"]*"', '""', line)
    return bool(_CASCADE_KEYWORD.search(sanitized))


class TestDropWithCascadeByDefault:
    """Default profile → DROP must include CASCADE."""

    @pytest.fixture(scope="class")
    def models(self):
        return {"my_view.sql": _VIEW_MODEL}

    def test_cascade_present_by_default(self, project):
        run_dbt(["run"])
        _, logs = run_dbt_and_capture(["--debug", "run"])

        drop_lines = _drop_view_lines(logs, "my_view")
        assert drop_lines, f"expected at least one DROP VIEW for my_view; logs:\n{logs}"
        for line in drop_lines:
            assert _has_cascade_keyword(line), line


class TestDropWithoutCascadeProfileLevel:
    """`drop_without_cascade=True` in the profile → DROP must omit CASCADE."""

    @pytest.fixture(scope="class")
    def profiles_config_update(self, dbt_profile_target):
        outputs = {"default": dbt_profile_target}
        outputs["default"]["drop_without_cascade"] = True
        return outputs

    @pytest.fixture(scope="class")
    def models(self):
        return {"my_view.sql": _VIEW_MODEL}

    def test_cascade_absent_when_profile_opts_in(self, project):
        run_dbt(["run"])
        _, logs = run_dbt_and_capture(["--debug", "run"])

        drop_lines = _drop_view_lines(logs, "my_view")
        assert drop_lines, f"expected at least one DROP VIEW for my_view; logs:\n{logs}"
        for line in drop_lines:
            assert not _has_cascade_keyword(line), line
