name: Publish results

inputs:
  file-name:
    description: File type for file name stub (e.g. "unit-tests")
    required: true
  python-version:
    description: Create an environment with the appropriate version of python and hatch installed
    required: true
  source-file:
    description: File to be uploaded
    required: true

runs:
  using: composite
  steps:
    - name: Get timestamp
      id: timestamp
      run: echo "ts=$(date +'%Y-%m-%dT%H_%M_%S')" >> $GITHUB_OUTPUT #no colons allowed for artifacts
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.file-name }}_${{ inputs.python-version }}-${{ steps.timestamp.outputs.ts }}.csv
        path: ${{ inputs.source-file }}
