name: Publish results

inputs:
  file-name:
    description: File type for file name stub (e.g. "unit-tests")
    required: true
  python-version:
    description: Python version for the file name stub (e.g. "3.9")
    required: true
  source-file:
    description: File to be uploaded
    required: true

runs:
  using: composite
  steps:
    - name: Get timestamp
      id: timestamp
      run: echo "ts=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT #no colons allowed for artifacts
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.file-name }}_python-${{ inputs.python-version }}_${{ steps.timestamp.outputs.ts }}.csv
        path: ${{ inputs.source-file }}
