name: Setup - `hatch`
description: Setup a python environment with `hatch` installed

inputs:
  setup-command:
    description: The command to setup development dependencies
    default: "python -m pip install hatch"
  python-version:
    description: The version of python to install
    default: "3.11"

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dev dependencies
      shell: bash
      run: ${{ inputs.setup-command }}

    - name: Add brew to the PATH
      shell: bash
      run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

    - name: Install pre-commit
      shell: bash
      run: brew install pre-commit
