# This workflow's purpose is to separate execution between serial and parallel for integration tests
# Having this separate from the main pull request checks allows us to run serial tests in parallel for multiple adapters
# E.g. serial tests for athena can run while serial tests for BQ do

name: "Serial/Parallel Integration tests"

on:
  workflow_call:
      inputs:
        is-serial-tests-run:
          description: "True for running serial tests. False for parallel"
          type: boolean
          required: true
        package:
          description: "Choose the package to test"
          type: string
          required: true

# only run this once per PR at a time
concurrency:
    group: ${{ github.workflow }}-${{ github.event.number }}
    cancel-in-progress: true

jobs:
    parallel-integration-tests:
        if: ${{ inputs.is-serial-tests-run == false }}
        uses: ./.github/workflows/_integration-tests.yml
        strategy:
            fail-fast: false
            matrix:
                package:
                  - ${{ inputs.package }}
                os: [ubuntu-22.04]
                python-version: ["3.9", "3.10", "3.11", "3.12"]
        with:
            package: ${{ matrix.package }}
            branch: ${{ github.event.pull_request.head.ref }}
            repository: ${{ github.event.pull_request.head.repo.full_name }}
            os: ${{ matrix.os }}
            python-version: ${{ matrix.python-version }}
            is-serial-test-run: false
        secrets: inherit

    serial-integration-tests:
        if: ${{ inputs.is-serial-tests-run == true }}
        uses: ./.github/workflows/_integration-tests.yml
        strategy:
            fail-fast: false
            max-parallel: 1
            matrix:
                package:
                    - ${{ inputs.package }}
                os: [ ubuntu-22.04 ]
                python-version: [ "3.9", "3.10", "3.11", "3.12" ]
        with:
            package: ${{ inputs.package }}
            branch: ${{ github.event.pull_request.head.ref }}
            repository: ${{ github.event.pull_request.head.repo.full_name }}
            os: ${{ matrix.os }}
            python-version: ${{ matrix.python-version }}
            is-serial-test-run: true
        secrets: inherit
