# **what?**
# Verifies python build on all code commited to the repository. This workflow
# should not require any secrets since it runs for PRs from forked repos. By
# default, secrets are not passed to workflows running from a forked repos.

# **why?**
# Ensure code for dbt meets a certain quality standard.

# **when?**
# This will run for all PRs, when code is pushed to main, and when manually triggered.

name: "Build"

on:
  push:
    branches:
      - "main"
  pull_request:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
  workflow_call:
    inputs:
      changelog_path:
        description: "Path to changelog file"
        required: true
        type: string

permissions: read-all

# will cancel previous workflows triggered by the same event and for the same ref for PRs or same SHA otherwise
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build, Test and publish to PyPi
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: Setup `hatch`
        uses: ./.github/actions/setup-hatch

      - name: Build `dbt-adapters`
        if: ${{ inputs.package == 'dbt-adapters' }}
        uses: ./.github/actions/build-hatch

      - name: Build `dbt-tests-adapter`
        if: ${{ inputs.package == 'dbt-tests-adapter' }}
        uses: ./.github/actions/build-hatch
        with:
          working-dir: "./dbt-tests-adapter/"

      - name: Setup `hatch`
        uses: ./.github/actions/setup-hatch

      - name: Build `dbt-adapters`
        if: ${{ inputs.package == 'dbt-adapters' }}
        uses: ./.github/actions/build-hatch

      - name: Build `dbt-tests-adapter`
        if: ${{ inputs.package == 'dbt-tests-adapter' }}
        uses: ./.github/actions/build-hatch
        with:
          working-dir: "./dbt-tests-adapter/"

      # this step is only needed for the release process
      - name: "Upload Build Artifact"
        if: ${{ github.event_name == 'workflow_call' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.version.outputs.version_number }}
          path: |
            ${{ inputs.changelog_path }}
            ./dist/
          retention-days: 3
