name: "Check changelog entry exists"

on:
    pull_request_target:
        types: [opened, reopened, labeled, unlabeled, synchronize]

defaults:
    run:
        shell: bash

permissions:
    contents: read
    pull-requests: write

jobs:
    changelog:
        uses: dbt-labs/actions/.github/workflows/changelog-existence.yml@main
        with:
            changelog_comment: 'Thank you for your pull request! We could not find a changelog entry for this change. For details on how to document a change, see [the contributing guide](https://github.com/dbt-labs/dbt-adapters/blob/main/CONTRIBUTING.md#adding-changelog-entry).'
            skip_label: 'Skip Changelog'
        secrets: inherit
