# **what?**
# Label a PR with a `community` label when a PR is opened by a user outside core/adapters
# Label an issue with a `triage` label when an issue is opened by a user outside core/adapters

# **why?**
# To streamline triage and ensure that community contributions are recognized and prioritized

# **when?**
# When a PR is opened, not in draft or moved from draft to ready for review
# When an issue is opened

name: Label community contributions

on:
  # have to use pull_request_target since community PRs come from forks
  pull_request_target:
    types: [opened, ready_for_review]
  issues:
    types: [opened]

defaults:
  run:
    shell: bash

permissions:
    pull-requests: write # labels PRs
    issues: write # labels issues
    contents: read # reads team membership

jobs:
  label_community_pr:
    # If this PR already has the community label, no need to relabel it
    # If this PR is opened and not draft, determine if it needs to be labeled
    # if the PR is converted out of draft, determine if it needs to be labeled
    if: |
      (
        github.event_name == 'pull_request_target'
        && !contains(github.event.pull_request.labels.*.name, 'community')
        && (
          (github.event.action == 'opened' && github.event.pull_request.draft == false)
          || github.event.action == 'ready_for_review'
        )
        && github.event.pull_request.user.type != 'Bot'
        && github.event.pull_request.user.login != 'dependabot[bot]'
      )
    uses: dbt-labs/actions/.github/workflows/label-community.yml@main
    with:
        github_team: 'core-group'
        label: 'community'
    secrets: inherit

  label_community_issue:
    # If this issue already has the triage label, no need to relabel it
    # If this issue is opened, determine if it needs to be labeled
    if: |
      (
        github.event_name == 'issues'
        && !contains(github.event.issue.labels.*.name, 'triage:product')
        && github.event.issue.user.type != 'Bot'
      )
    uses: dbt-labs/actions/.github/workflows/label-community.yml@main
    with:
        github_team: 'core-group'
        label: 'triage:product'
    secrets: inherit
