name: "Run pre-commit autoupdate"

on:
  pull_request:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  precommit-autoupdate:
    name: "Run pre-commit autoupdate"
    uses: dbt-labs/actions/.github/workflows/pre-commit-autoupdate.yml@pre-commit-auto-update
