name: "Run pre-commit autoupdate"

on:
  schedule:
    - cron: "30 1 * * SAT"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  precommit-autoupdate:
    name: "Run pre-commit autoupdate"
    uses: dbt-labs/actions/.github/workflows/pre-commit-autoupdate.yml
    secrets:
      TOKEN: ${{ secrets.FISHTOWN_BOT_PAT }}
      SLACK_WEBHOOK_PR_URL: ${{ secrets.SLACK_DEV_ADAPTER_PULL_REQUESTS }}
      SLACK_WEBHOOK_ALERTS_URL: ${{ secrets.SLACK_DEV_ADAPTER_ALERTS }}
