# **what?**
# When triaging submissions, we sometimes need more information from the issue creator.
# In those cases we remove the `triage` label and add the `awaiting_response` label.
# Once we receive a response in the form of a comment, we want the `awaiting_response` label removed
# and the `triage` label added so that we are aware that the issue needs action.

# **why?**
# This automates a part of issue triaging while also removing noise from triage lists.

# **when?**
# This will run when a comment is added to an issue and that issue has an `awaiting_response` label.

name: Resubmit for Triage

on: issue_comment

defaults:
  run:
    shell: bash

permissions:
  issues: write

jobs:
  triage_label:
    if: contains(github.event.issue.labels.*.name, 'awaiting_response')
    uses: dbt-labs/actions/.github/workflows/swap-labels.yml@main
    with:
      add_label: "triage"
      remove_label: "awaiting_response"
    secrets: inherit # this is only acceptable because we own the action we're calling
